aws_region = "us-east-1"
cluster_name = "retail-store"
environment = "stage"
kubernetes_version = "1.33"
vpc_cidr = "10.1.0.0/16"
github_repository = "iemafzalhassan/retail-store-sample-app"
assume_role_arn = "arn:aws:iam::390112040038:role/TerraformExecutionRole"